baseurl = "http://andrewwalker.github.io/statefultransitions/"
languageCode = "en-us"
title = "Stateful Transitions"
theme = "purehugo"
Paginate = 5
disqusShortname = "statefultransitions"

[params]
    description = "Life-long learning in mathematics, science and computing"
    twitter = "walkera101"
    github = "AndrewWalker"
